"""Data Transfer Objects."""

from .music_dtos import (
    MusicGenerationRequest,
    MusicGenerationResponse,
    JobStatusResponse,
    MusicAnalysisRequest,
    MusicAnalysisResponse,
    TransformationRequest,
    TransformationResponse,
    MusicalPieceResponse,
    PieceListResponse,
    ErrorResponse,
    ChatRequest,
    ChatResponse,
    PatternData,
    ComparisonRequest,
    ComparisonResponse,
    ProcessRequest,
    ProcessResponse,
    ProcessPatternData,
)

__all__ = [
    "MusicGenerationRequest",
    "MusicGenerationResponse",
    "JobStatusResponse",
    "MusicAnalysisRequest",
    "MusicAnalysisResponse",
    "TransformationRequest",
    "TransformationResponse",
    "MusicalPieceResponse",
    "PieceListResponse",
    "ErrorResponse",
    "ChatRequest",
    "ChatResponse",
    "PatternData",
    "ComparisonRequest",
    "ComparisonResponse",
    "ProcessRequest",
    "ProcessResponse",
    "ProcessPatternData",
]
